### ISSUE TITLE
Remove unused Java classes

### ISSUE THREAD

**Issue by ardlank** [gouri-panda/XPlayer#15]
app/src/main/java/com/one4ll/xplayer/MyContentProvider.java
app/src/main/java/com/one4ll/xplayer/TaskContract.java
app/src/main/java/com/one4ll/xplayer/TaskDbHelper.java

These files are not used in the app. Deleting them from the repo will make the repo 100% Kotlin :)

**Comment by ardlank** [comment]
https://github.com/gouri-panda/XPlayer/pull/16

**Comment by gouri-panda** [comment]
@ardlank Nope thats not necessary.
