### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/XPlayer#31]
In our readme file, our contributions sections look weird. It would be better if we updated it.

**Comment by vishwast03** [comment]
Hey @gouri-panda 
I am Vishwas Tyagi. I would like to work on this.

**Comment by gouri-panda** [comment]
@vishwast03 Thanks! Go ahead!

**Comment by vishwast03** [comment]
@gouri-panda  Thanks for your reply. I will get back soon with updated readme file.

**Comment by iamansoni** [comment]
Is this issue still need to be addressed? If yes, you can assign it to me.
I would like to work on this task!

**Comment by gouri-panda** [comment]
@iamansoni Thank you! Go ahead!
