### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by iamansoni** [gouri-panda/XPlayer#37]
I would like to add a `LICENSE` for this project. 
In order to make this repository truly open source, we'll need to license it so that others are free to use, change, and distribute this software.

**Comment by gouri-panda** [comment]
Yes, @iamansoni Go ahead!

**Comment by iamansoni** [comment]
I would really like to work on this issue under the `GSSOC` tag as a GSSOC participant so my contributions can be counted! Hope you won't mind tagging it for the same!😅
