### ISSUE TITLE
Music Fragment is crashing

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/XPlayer#5]
**How to reproduce**
Open music fragment and then crash
**Expected behavior**
Open music fragment and it will not crash

**Comment by abkoradiya** [comment]
Can you describe more about the crash? Because I am not facing a crash. And I think music list is not coming in that fragment,

**Comment by gouri-panda** [comment]
@abkoradiya do you have any music files? if no then download it then open the music fragment and then it should crash it by now.

**Comment by abkoradiya** [comment]
But where you have call that function for retrieve music files?

![image](https://user-images.githubusercontent.com/26247850/95022246-97b34700-0693-11eb-859d-605d30732a3a.png)

`getMusicList` function from `MusicViewModel` not called anywhere.

**Comment by gouri-panda** [comment]
> But where you have call that function for retrieve music files?
> 
> ![image](https://user-images.githubusercontent.com/26247850/95022246-97b34700-0693-11eb-859d-605d30732a3a.png)
> 
> `getMusicList` function from `MusicViewModel` not called anywhere.

It's getting from live data

**Comment by abkoradiya** [comment]
![image](https://user-images.githubusercontent.com/26247850/95022538-93882900-0695-11eb-9f01-fcbc04517a1c.png)

But it is not used anywhere?

**Comment by abkoradiya** [comment]
Have you checked this?

**Comment by gouri-panda** [comment]
Issue solved by #25
