### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/XPlayer#9]
A Readme file is the documentation of repository. Update readme file with the repository info.

**Comment by HarisHoulis** [comment]
Hi @gouri-panda, do you have any recommendations about the update of the readme? Should i put a couple of screenshots?

**Comment by gouri-panda** [comment]
Thank you @Charis1331 .
>Should I put a couple of screenshots?

That would be great!
>do you have any recommendations about the update of the readme?

Yes, I want to include all library list that this project is using now and also their link in the `Readme.md` file.

**Comment by HarisHoulis** [comment]
Hi @gouri-panda, please take a look at #12; I will create a different issue for the screenshots,

**Comment by HarisHoulis** [comment]
Can you also add the "hacktoberfest" topic to the repo please? Thanks in advance.

**Comment by gouri-panda** [comment]
> Can you also add the "hacktoberfest" topic to the repo please? Thanks in advance.

sure @Charis1331

**Comment by HarisHoulis** [comment]
I post this here in case it interests you:
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by gouri-panda** [comment]
> I post this here in case it interests you:
> https://hacktoberfest.digitalocean.com/hacktoberfest-update

Thank you @Charis1331 .
